added new payload keys
edganiukov/apns pull request #1
Opened 2020-10-12 19:38 UTC by Apurer

2020-10-12 19:46 UTC, Apurer commented
Based on [Apple Documentation Generating a Remote Notification](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification)

2020-10-15 12:55 UTC, edganiukov requested changes
Thanks for the PR, just a small comment regarding.

2020-10-15 12:55 UTC, edganiukov commented on notification.go
> +	TargetContentId string `json:"target-content-id,omitempty"`
```suggestion
	TargetContentID string `json:"target-content-id,omitempty"`
```

2020-10-16 20:03 UTC, Apurer commented on notification.go
> +	TargetContentId string `json:"target-content-id,omitempty"`
Sure :)

2020-10-17 09:25 UTC, edganiukov approved these changes

2020-10-17 09:25 UTC, merged